### ISSUE TITLE
Added your package to arch linux aur

### ISSUE THREAD

**Issue by rigred** [ianzhao05/textshot#12]
Just a friendly heads up that I've added your package to the archlinux aur and it will keep itself updated based on the latest git commits to the github repo.
https://aur.archlinux.org/packages/textshot-git

So for arch users it's as easy as installing `textshot-git` with their favourite aur helper.
`yay -S textshot-git`

Also is there a way to make textshot pause the desktop (animations like the gif on this page)?
Currently it keeps on animating while in box select mode.

Thanks for the great tool!

**Comment by ianzhao05** [comment]
Thank you, glad you like it. I've added a note in the README about installation from the AUR. I will open an issue about pausing the desktop and work on it in the near future.
