### ISSUE TITLE
能不能集成中文的OCR识别能力呀？

### ISSUE THREAD

**Issue by grasswolfs** [ianzhao05/textshot#15]
好项目呀，感觉很实用，不过我看现在应该是只有英文，之前chineseocr有17M中文识别模型模型，
还有最近百度飞桨新发的，https://github.com/PaddlePaddle/PaddleOCR 只有9M的模型，效果好像还更好一些，
不知道几位大佬，最近有没有计划把中文识别能力集成进去呀？

**Comment by ianzhao05** [comment]
Please speak in English.

I believe you are asking about Chinese language support. If you download the Chinese language files for Tesseract-OCR and run the script like `python textshot.py chi_sim` (for Chinese simplified), it should work.
