### ISSUE TITLE
Produces a grey screen when called

### ISSUE THREAD

**Issue by Anirudh171202** [ianzhao05/textshot#20]
Everything works except the starting window when textshot is called, which is fully grey.
OS : Manjaro Linux KDE
![Screenshot_20200617_164541](https://user-images.githubusercontent.com/38956105/84894342-48ceab00-b0be-11ea-8a43-87ecfb7db40f.png)

**Comment by ianzhao05** [comment]
Are you up to date with the `master` branch? It used to require compositing from the desktop environment, but now it shouldn't.
