### ISSUE TITLE
Hotkey opening failed, but can be performed in CMD

### ISSUE THREAD

**Issue by Rus0wes** [ianzhao05/textshot#21]
Use the textShot.ahk script that comes with it
Please guide

![EX8IJFEAIOPBPI)9(P% LBH](https://user-images.githubusercontent.com/67153993/85136582-65abdf80-b272-11ea-9609-0d8999da9800.png)

**Comment by ianzhao05** [comment]
You need to install AutoHotkey, which can be found at https://www.autohotkey.com/

After you install AutoHotkey, you can run the script by opening it with the program. It will run and listen for the hotkey in the background.

**Comment by Rus0wes** [comment]
But I already have Autohotkey installed, and the hotkeys don't clash.However, it cannot be executed, I would like to ask what "pythonW. exe" does, and I have tried to manually open it without any effect

**Comment by ianzhao05** [comment]
`pythonw` is simply `python` but with no console window attached. Remember to modify the script if the path to the interepreter is different. The script currently points to an interpreter created as part of a virtual environment `.venv`.

**Comment by Rus0wes** [comment]
Strangely, I executed the script using the hotkey with just a flash of the mouse cursor.Do you know the reason?My script was originally downloaded and has not been modified.Do I need to modify it?Is that the reason?

**Comment by ianzhao05** [comment]
As I said, you should modify it if the location of your Python interpreter differs from the one currently in the script. Did you use a virtual environment, or did you install the dependencies to the global Python?

**Comment by Rus0wes** [comment]
Do you mean that the path should be the path of the Python interpreter, not through the virtual environment? Is the python interpreter name "Python.exe"?

**Comment by ianzhao05** [comment]
The virtual environment has its own interpreter (the Python executable). If you installed the dependencies in the virtual environment, use the path to that interpreter (`.\<your venv name>\Scripts\pythonw.exe`). Otherwise, if you installed the dependencies to your global Python interpreter, then use the path to that (usually just `pythonw`). Again, you should use `pythonw` instead of `python` because it does not show a console window.
