### ISSUE TITLE
Tesseract Process Timeout

### ISSUE THREAD

**Issue by edwardsaunders7** [ianzhao05/textshot#23]
Appears to not work on more than 5 words at a time, presents with error 

> "TextShot"
>"An error occurred when trying to process the image: Tesseract process timeout"

**Comment by ianzhao05** [comment]
Could you share the image that caused it to fail? This is a Tesseract issue that is caused by the input image. You can also try increasing the timeout in the code (default 2 seconds).

**Comment by edwardsaunders7** [comment]
It doesn't appear to be an input image related issue, I can try it on multiple things and the same errors occur. I've attached some images that I sampled that produced the result

![2020-06-27_00-28_1](https://user-images.githubusercontent.com/51308267/85908537-61049f80-b80d-11ea-903f-bba6ae221c65.png)

![2020-06-27_00-30](https://user-images.githubusercontent.com/51308267/85908563-7a0d5080-b80d-11ea-8bb2-6cee8bed68eb.png)

![2020-06-27_00-31](https://user-images.githubusercontent.com/51308267/85908616-a7f29500-b80d-11ea-8f4d-61a3e203f969.png)

**Comment by ianzhao05** [comment]
Ok, thanks. Does it work if the text is dark on a light background? If not, maybe the screenshot is taking the wrong image.

**Comment by edwardsaunders7** [comment]
Colour doesn't seem to have an effect, just tested with these two inputs:
![2020-06-27_00-38_1](https://user-images.githubusercontent.com/51308267/85908810-a2497f00-b80e-11ea-8423-554a0f75966d.png)
![2020-06-27_00-38](https://user-images.githubusercontent.com/51308267/85908812-a2e21580-b80e-11ea-8e7a-ec2c2b2e09f5.png)

**Comment by ianzhao05** [comment]
Ok, if you add something like `pil_img.show()` at around line 85, does it show the correct image? By the way, what OS are you on?

**Comment by edwardsaunders7** [comment]
Added `pil_img.show()` - shows the proper image.


Editing the timeout on line 90:
 - 10 seconds allows for more text to be converted before the timeout error occurs, however now means there is a much longer delay. 

- When attempting to copy large bodies of text the timeout error still occurs when the timeout is small,  tested with increased time (30 seconds - not enough, 1 minute - works). For some reason changing the timeout to 60 seconds prevents the error, and also allows for the conversion to happen without delay (completes text conversion within 15 seconds), unlike with 10 seconds which shows a noticeable delay (over a minute).

On Manjaro Linux.

**Comment by ianzhao05** [comment]
The behaviour you are describing is really strange. On my laptop (mid-range specs), it usually takes around a second, even for large amounts of text. If you don’t mind, can you test with the `tesseract` executable directly and see how long it takes? https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage

**Comment by edwardsaunders7** [comment]
Tested with a few input images. 

- Image 1: Tesseract = 26 seconds, textshot = 42 seconds
- Image 2: Tesseract = 20 seconds, textshot = 29 seconds
- Image 3: Tesseract = 30 seconds, textshot = 28 seconds
- Image 4: Tesseract = 11 seconds, textshot = 15 seconds

**Comment by ianzhao05** [comment]
Thank you for your testing. It seems that Tesseract is taking a lot longer for you. What kind of processor does your computer have? Also, what is your Tesseract version? My PC has an i7-6700K, and my laptop an i5-7200U, and I haven't really had any timeout issues. I do agree that 2 seconds is too low however, so I will update that.

**Comment by edwardsaunders7** [comment]
I am running a "4 x Intel Core i5-4690K CPU @ 3.50GHz" with "15.5GiB of RAM"

I tested textshot on my laptop and my desktop previously and had no issues, it only seemed to occur when I reinstalled textshot today. No idea why tesseract is taking longer for me, let me test a few more things and see if I can find an answer.

**Comment by edwardsaunders7** [comment]
Update:
I just realised I had my VPN on, and so network speeds are likely the cause of the issue

I just disconnected my VPN, and tesseract (and textshot) are both working within a few seconds (using all the same test images)

Apologies for not realising that could be the issue beforehand!

**Comment by ianzhao05** [comment]
I honestly didn't know before that Tesseract was affected by network speeds! No apology needed; glad it works now :)
