### ISSUE TITLE
Cropping depends on screen resolution

### ISSUE THREAD

**Issue by IshaanOhri** [ianzhao05/textshot#24]
Cropping is incorrect at times. It depends on screen resolution. I have a 4k display and it wasn't performing as expected

**Comment by ianzhao05** [comment]
Thanks for reporting this. Can you elaborate? What OS are you using? If you add `pil_img.show()` at around line 85, does it show the correct or incorrect image? If you don't mind to do some debugging, if you print `self.start` and `self.end` in `mouseReleaseEvent` at line 68, do they represent the correct coordinates?

**Comment by IshaanOhri** [comment]
I'm using Mac OS 11.0 Beta. I had already debugged the code before opening the issue. So my display is 2560 x 1600 but the window size shown is 1680 x 1050. Either you need to change the resolution of the window or probably scale down the screenshot to the window resolution.

**Comment by ianzhao05** [comment]
Ok, I am aware that is is a bit buggy on macOS. I will try to find a fix.

**Comment by IshaanOhri** [comment]
I have taken inspiration from your project and created a similar one of my own with added features and have solved this issue in there. You could refer [Capture](https://github.com/IshaanOhri/Capture)

**Comment by ianzhao05** [comment]
Hmm, the link worked a second ago but now it doesn't? If you know how to solve this issue, please feel free to make a pull request! I am interested in seeing how you did it.

**Comment by IshaanOhri** [comment]
The link is working fine. I guess it might be some server issue or something.
By the way, PR created.
I'm therefore closing the issue.
