### ISSUE TITLE
Text not being copied to clipboard and sometimes words are translated to french language !

### ISSUE THREAD

**Issue by RaviPabari** [ianzhao05/textshot#26]
I have created a shortcut in my Ubuntu for textshot and whenever I use it (some times not all the time) the text is copied in French and Not being copied to clipboard at all(this is main issue), I knew it was in French because it was shown in notification :/

**Comment by ianzhao05** [comment]
Can you please share what command you are running? What image are you using it on? Can you give an example?

**Comment by RaviPabari** [comment]
1) Command for shortcut I am using without any extra arguments
`/home/ravi/anaconda3/bin/python  /home/ravi/utilities/textshot/textshot.py`
2) SS for where I got this translated to French ( I tried to recreate this error several time but managed to find here in settings everytime I take the snap in settings I got this translated to French and couldn't paste it idk why for pasting I tried `ctrl+v`
images:
In the notification area you can see it translated to French  or Idk what lang is that 
![1](https://user-images.githubusercontent.com/46424422/89107896-da696080-d451-11ea-8927-8f42b85cef5f.png)
![2](https://user-images.githubusercontent.com/46424422/89107899-dfc6ab00-d451-11ea-9dab-1f6ce07cd5ea.png)

**Comment by ianzhao05** [comment]
It's not any language; just a bunch of garbage characters lol. The image in the screenshot is really noisy. It works best if you just have one piece of text with a uniform background and text colour. The dialog box in your case has multiple different colours, and the text is in multiple places.

**Comment by RaviPabari** [comment]
LOL I thought it was French SMH...
But the problem is not solved yet still the text when detected properly are not copied to clipboard and I can't paste them :/

**Comment by ianzhao05** [comment]
Examples of good images:
![image](https://user-images.githubusercontent.com/34221171/89108142-5a141280-d3f3-11ea-9c94-f39616e84cc5.png)
![image](https://user-images.githubusercontent.com/34221171/89108155-6ac48880-d3f3-11ea-8595-df7053eb591b.png)
![image](https://user-images.githubusercontent.com/34221171/89108218-deff2c00-d3f3-11ea-8b38-d08ab8fd032c.png)

Examples of bad images:
![image](https://user-images.githubusercontent.com/34221171/89108264-17066f00-d3f4-11ea-8091-b5df0cc5a05f.png)
![image](https://user-images.githubusercontent.com/34221171/89108318-98f69800-d3f4-11ea-838a-6bad6bf211a8.png)
![image](https://user-images.githubusercontent.com/34221171/89108390-48cc0580-d3f5-11ea-8064-17bac0f3c215.png)

**Comment by RaviPabari** [comment]
Okay I understood now, but still what the problem I am facing is that the text is detected but Not COPIED to the clip board. In the notification I can see that it says the ` "copied"  'the text' ` but when I hit `ctrl+v` nothing gets pasted.
I on the new picture but still same :/
I took the screenshot when the program was running and I dragged the mouse and created that mini window for where I have to detect the text and before releasing the mouse I took this so you can see where I tested
![Screenshot from 2020-08-02 00-25-00](https://user-images.githubusercontent.com/46424422/89108562-3c789480-d457-11ea-995f-7a4258f549c3.png)

**Comment by ianzhao05** [comment]
Yeah, that is a good image. If you see the correct text in the notification, but you can't paste it, then something must be up with the clipboard function. My bet is that `xclip` is not installed. Can you do `sudo apt install xclip` and try again?

**Comment by RaviPabari** [comment]
Done done done working now thanks bro.
I have made a PR where I have added an extra line in readme for installing xclip if not installed in some distros :)
Thanks :100:
