### ISSUE TITLE
textshot on macOS Big Sur

### ISSUE THREAD

**Issue by hasantahir** [ianzhao05/textshot#28]
Hi, 

On macOS 11.1, invoking `python textshot.py` throws a Qt GUI error:
```
QPixmap::fromImage: QPixmap cannot be created without a QGuiApplication
QPixmap: Must construct a QGuiApplication before a QPixmap
```
Any suggestions? This worked fine before updating to Big Sur. Thank you!

EDIT: This has been tried with a virtual environment.

**Comment by ianzhao05** [comment]
Hi, I made a fix that should get rid of the error. The main issue is that Tesseract was not found in the system path, but the notification used Qt methods before an application was initialized. Can you test out that branch?

**Comment by hasantahir** [comment]
Thanks for addressing this so soon. Before trying out the branch, I updated the dependencies `PyQt5` to version 5.15.2 as opposed to the one mentioned in the `requirements.txt`. It fixed the mentioned error.

**Comment by ianzhao05** [comment]
Alright, glad that it works. I'll update the dependencies tool.
