### ISSUE TITLE
Size limitation for text, and sometimes prior OCR conversion in clipboard is not replaced with new OCR conversion

### ISSUE THREAD

**Issue by sjscotti** [ianzhao05/textshot#45]
Hi
I think this is a really cool idea to make OCR simple to do and allows for correcting OCR mistakes very easily.  
I am on a Windows machine and I find that I need to  OCR a large text image in parts because it doesn't handle 
a lot of text well.  Is there a recommended maximum amount of text that should be selected for conversion?
But even doing OCR in parts, some areas appear to be captured and the "spinning wheel" indicates that
a conversion is being done.  But when pasting the text that is in the clipboard to notepad++, it is the text from a prior conversion.
If there is an error in the conversion process, I can't find where it is displayed.  Can you please give me some pointers
on getting around these issues?
Thanks!

**Comment by sjscotti** [comment]
I found at least one of my problems.  I created an anaconda environment for textshot and did the `pip install -r requirements.txt`.  But in searching on the internet, it seem for anaconda I needed to install the `win32api` used by `win10toast`  with `conda install pywin32` and not `pip`.  Before `win10toast` wasn't finding `win32api`.  I'm still exploring whether this addresses the other points I brought up, but for now I'll close this issue.

**Comment by ianzhao05** [comment]
Hi, thanks for raising the issue. If you run it from the command line, it should print something that might be able to assist with troubleshooting. With large bodies of text, there is a 5 second timeout which should be enough for most use cases, but you can play with that value on [line 92 of `textshot.py`](https://github.com/ianzhao05/textshot/blob/master/textshot.py#L92) to see if increasing it helps. Generally, a large text image should be fine.

That's interesting regarding `conda` + `pip` not installing `win32api`, thanks for testing that out!

**Comment by sjscotti** [comment]
Thanks for the speedy reply!  Another thing that I have done which seems to improve my results is to set the `--psm` flag in the call on line 92 of textshot.py.   So that line now reads...
```
            pil_img, timeout=5, lang=(sys.argv[1] if len(sys.argv) > 1 else None), config="--psm 6" 
```
At least that is what is working better for me..

**Comment by sjscotti** [comment]
Thanks for the speedy reply!  Another thing that I have done which seems to improve my results is to set the `--psm` flag in the call on line 92 of textshot.py.   So that line now reads...
```
            pil_img, timeout=5, lang=(sys.argv[1] if len(sys.argv) > 1 else None), config="--psm 6" 
```
At least that is what is working better for me..

**Comment by ianzhao05** [comment]
That's a good idea to change the PSM. I might add a command line option to make the config easier to customize.
