### ISSUE TITLE
Screen turns black when opening textshot

### ISSUE THREAD

**Issue by DahilerMehvOlur** [ianzhao05/textshot#50]
When I run textshot opposite this problem. I show in video. Sorry bad english if I mistake anywhere.

https://user-images.githubusercontent.com/112520722/187555440-6fd7f968-262d-4c47-869e-a7388f121fed.mp4

**Comment by ianzhao05** [comment]
Thanks for opening the issue and for the detailed video.

You are on Linux, correct? I'm assuming this is an issue with transparency and your specific desktop. As a workaround, you can comment out [line 47 of `textshot.py`](https://github.com/ianzhao05/textshot/blob/master/textshot.py#L47). I will look into this further!

**Comment by DahilerMehvOlur** [comment]
Yes. I run manjaro kde plasma. And you are correct I customized my desktop. I use layan theme. But I am not a programmer. In this sentence (As a workaround, you can comment out line 47 of textshot.py) you say to add hashtag to the head of the line?

**Comment by DahilerMehvOlur** [comment]
Yes. I run manjaro kde plasma. And you are correct I customized my desktop. I use layan theme. But I am not a programmer. In this sentence (As a workaround, you can comment out line 47 of textshot.py) you say to add hashtag to the head of the line?

**Comment by ianzhao05** [comment]
That's interesting, I'm not sure why there would be a black rectangle if you commented out the line that draws the rectangle. I can't reproduce this, so I'm not quite sure what would be causing it. You can maybe try commenting out [lines 45-47](https://github.com/ianzhao05/textshot/blob/1f8e23ce2b1c3e991993cde35ee856f2a1e7cb88/textshot.py#L45-L47).

**Comment by DahilerMehvOlur** [comment]
Unfortunately, nothing has changed. The tool you do is really useful. Just in the style I'm looking for. It can cut it with a single click and make it. It does not require any program interface. It's doing his job with only one shortcut button. That's why I don't want to give up the tool. So you know, just like this, there is a tool alternative?

**Comment by ianzhao05** [comment]
I still can't think of why there would be the black rectangle. Thank you for testing and reporting this bug. You can try something like https://github.com/dynobo/normcap; maybe it will work better on your machine.

**Comment by DahilerMehvOlur** [comment]
I tried the normcap. But this time he didn't do OCR instead of a rectangular problem. :D. So the normcap was already eliminated. Continue to use textshot. After all, he does his job well, although not comfortable. Thanks for tool. After all, the rectangular problem is not because of you. Because of the theme I use.
❤️Thank you for your interest❤️
