### ISSUE TITLE
screenshot "E:\>cd github" output -->"INFO: Copied "AR" to the clipboard"

### ISSUE THREAD

**Issue by linfengca** [ianzhao05/textshot#55]
screenshot "E:\>cd github" output -->"INFO: Copied "AR" to the clipboard"

the command line test info:

E:\github>cd..

E:\>cd github

E:\github>cd textshot

E:\github\textshot>python textshot.py
**INFO: Copied "E:\github>cd. .
AR

E:\github>cd textshot" to the clipboard**

E:\github\textshot>python textshot.py chi_sim
**INFO: Copied "ET
E:N>cd github

E:Ngithub>cd textshot" to the clipboard**

E:\github\textshot>

**Comment by ianzhao05** [comment]
Hi there, could you please be a bit more specific with what the issue is? To me, the output has a couple errors but looks acceptable by OCR standards.

**Comment by linfengca** [comment]
If this type of problem is acceptable according to the OCR standards, there will be no problem, thanks.

**Comment by ianzhao05** [comment]
Great! In general, OCR will do better on text with actual words/sentences, as it can guess words based on language, and it sometimes doesn't do as well in text with many symbols.
